#!/usr/bin/perl -w
use strict;
use warnings;
print "Program takes in newick format tree generated by PhyML program; replaces short name with long names\n";
print "usage: perl replace_short_to_long_list.pl <phyml_tree_file> <edited_short_to_long_taxa_name_file>\n";
print "The taxa file should be formatted as long_name\tshort_name\n";
print "The diting of taxa names can be performed in MS Excel primarily. It is strongly adviced to keep at least
the accession number of the sequence for easy back tracking\n";
####Tree file input####

my $f=$ARGV[0]; 
open IN,$f or die "Could not open file tree file";
my $f1=<IN>;

####Taxa name change file input####

my $f2 = $ARGV[1];
open IN2, $f2 or die "Could not open file taxa-name file";
@file2 = <IN2>;

foreach my $line(@file2)
	{
		chomp $line;
		my @eachline = split(/\t/, $line);
		my $short = $eachline[1];
		#print $short,"\n";
		my $long = $eachline[0];
		#print $long,"\n";
		$f1 =~ s/$short:/$long:/g;
	}

open OUT,">$f\_final_tree.nwk" or die "Error in file formatting of taxa file";
print OUT $f1;	
